package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_UNIQUENESS_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Friday, February 8, 2008 7:23:14 PM GMT-08:00
*/

public interface ID_UNIQUENESS_POLICY_ID
{

  /**
  	 * The value representing ID_UNIQUENESS_POLICY_ID.
  	 */
  public static final int value = (int)(18);
}
